# Generated by Django 3.0 on 2022-12-02 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('lasagne', 'Lasagne'), ('lattuga', 'Lattuga'), ('formaggio', 'Formaggio'), ('pizza', 'Pizza'), ('carne', 'Carne'), ('pesce', 'Pesce')], default='lattuga', max_length=256)),
                ('calories', models.IntegerField(default=0)),
                ('totalfat', models.IntegerField(default=0)),
                ('saturatedfat', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('cholestorol', models.IntegerField(default=0)),
                ('sodium', models.IntegerField(default=0)),
                ('fiber', models.IntegerField(default=0)),
                ('sugars', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('surname', models.CharField(max_length=256)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('name', models.CharField(choices=[('Colazione', 'Colazione'), ('Pranzo', 'Pranzo'), ('Cena', 'Cena'), ('Merenda', 'Merenda')], default='colazione', max_length=256)),
                ('foods', models.ManyToManyField(to='core.Food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User'),
        ),
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField()),
                ('day_of_week', models.CharField(choices=[('Lunedì', 'Lunedì'), ('Martedì', 'Martedì'), ('Mercoledì', 'Mercoledì'), ('Giovedì', 'Giovedì'), ('Venerdì', 'Venerdì'), ('Sabato', 'Sabato'), ('Domenica', 'Domenica')], default='Lunedì', max_length=20)),
                ('meals', models.ManyToManyField(to='core.Meal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.User')),
            ],
        ),
    ]
