# Generated by Django 4.2.5 on 2023-10-16 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightmeasure',
            options={'verbose_name': 'Pesata', 'verbose_name_plural': '10. Pesate'},
        ),
    ]
