# Generated by Django 3.0 on 2023-02-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='uuid',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='uuid',
        ),
        migrations.AddField(
            model_name='diet',
            name='deleted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='diet',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=7, verbose_name='Quantità (g)'),
        ),
    ]
