# Generated by Django 4.2.5 on 2023-10-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_weightmeasure_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightmeasure',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True),
        ),
    ]
