# Generated by Django 3.0 on 2023-02-11 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230211_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diet',
            name='deleted',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='diet',
            name='patient',
        ),
        migrations.AlterField(
            model_name='diet',
            name='day_of_week',
            field=models.CharField(choices=[('Lunedì', 'lun'), ('Martedì', 'mar'), ('Mercoledì', 'mer'), ('Giovedì', 'gio'), ('Venerdì', 'ven'), ('Sabato', 'sab'), ('Domenica', 'dom'), ('Lunedì-Venerdì', 'lun-ven'), ('Tutti i giorni', 'all')], default='Lunedì', max_length=20),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(choices=[('Colazione', 'breakfast'), ('Pranzo', 'launch'), ('Cena', 'dinner'), ('Merenda', 'snack')], default='colazione', max_length=256),
        ),
        migrations.CreateModel(
            name='PatientProgram',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('dieta', models.ManyToManyField(to='core.Diet')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Patient')),
            ],
        ),
    ]
