# Generated by Django 3.0 on 2023-02-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230211_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diet',
            name='day_of_week',
            field=models.CharField(choices=[('lun', 'Lunedì'), ('mar', 'Martedì'), ('mer', 'Mercoledì'), ('gio', 'Giovedì'), ('ven', 'Venerdì'), ('sab', 'Sabato'), ('dom', 'Domenica'), ('ven', 'Lunedì-Venerdì'), ('all', 'Tutti i giorni')], default='Lunedì', max_length=20),
        ),
    ]
