# Generated by Django 3.0 on 2023-02-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230214_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='kjoules',
            field=models.FloatField(default=0),
        ),
    ]
