# Generated by Django 3.0 on 2023-02-14 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_food_kjoules'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodsubstitute',
            options={'verbose_name': 'Food Substtute', 'verbose_name_plural': 'Food Substitute'},
        ),
        migrations.RemoveField(
            model_name='foodsubstitute',
            name='food',
        ),
        migrations.AddField(
            model_name='food',
            name='substitute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.FoodSubstitute'),
        ),
    ]
