# Generated by Django 3.0 on 2023-03-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230314_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodsubstitute',
            options={'verbose_name': 'Food Substitute', 'verbose_name_plural': 'Food Substitute'},
        ),
        migrations.RenameField(
            model_name='foodsubstitute',
            old_name='calories',
            new_name='substitute_calories',
        ),
        migrations.RenameField(
            model_name='foodsubstitute',
            old_name='carbs',
            new_name='substitute_carbs',
        ),
        migrations.RenameField(
            model_name='foodsubstitute',
            old_name='cholestorol',
            new_name='substitute_cholestorol',
        ),
        migrations.RenameField(
            model_name='foodsubstitute',
            old_name='fiber',
            new_name='substitute_fiber',
        ),
        migrations.RenameField(
            model_name='foodsubstitute',
            old_name='protein',
            new_name='substitute_protein',
        ),
        migrations.RenameField(
            model_name='foodsubstitute',
            old_name='quantity',
            new_name='substitute_quantity',
        ),
        migrations.RenameField(
            model_name='foodsubstitute',
            old_name='saturatedfat',
            new_name='substitute_saturatedfat',
        ),
        migrations.RenameField(
            model_name='foodsubstitute',
            old_name='sodium',
            new_name='substitute_sodium',
        ),
        migrations.RenameField(
            model_name='foodsubstitute',
            old_name='sugars',
            new_name='substitute_sugars',
        ),
        migrations.RenameField(
            model_name='foodsubstitute',
            old_name='totalfat',
            new_name='substitute_totalfat',
        ),
    ]
