# Generated by Django 3.0 on 2023-02-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20230214_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='substitute',
        ),
        migrations.AddField(
            model_name='foodsubstitute',
            name='food',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Food'),
        ),
    ]
