# Generated by Django 3.0 on 2023-02-14 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20230214_1646'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodsubstitute',
            options={'verbose_name': 'Food Substitute', 'verbose_name_plural': 'Food Substitute'},
        ),
        migrations.RemoveField(
            model_name='foodsubstitute',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodsubstitute',
            name='name',
        ),
        migrations.AddField(
            model_name='foodsubstitute',
            name='food_substitute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_substitute', to='core.Food'),
        ),
        migrations.AddField(
            model_name='foodsubstitute',
            name='food_to_substitute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food_to_substitute', to='core.Food'),
        ),
    ]
