# Generated by Django 3.0 on 2023-08-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20230314_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='advice/')),
                ('type', models.CharField(choices=[('Consigli', 'advice'), ('Sostituzioni', 'swap')], default='advice', max_length=256)),
                ('is_active', models.BooleanField(default=True)),
                ('expire_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
