# Generated by Django 3.0 on 2023-08-27 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='advice',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
