# Generated by Django 3.0 on 2023-08-28 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_advice_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advice',
            name='type',
            field=models.CharField(choices=[('Consigli', 'Consigli'), ('Sostituzioni', 'Sostituzioni')], default='advice', max_length=256),
        ),
    ]
