# Generated by Django 3.0 on 2023-08-29 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20230828_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='foods',
        ),
        migrations.AlterField(
            model_name='food',
            name='calories',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Calorie ogni 100 g/ml', max_digits=7),
        ),
        migrations.CreateModel(
            name='Portion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('unity', models.CharField(blank=True, default='g', max_length=255, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Food')),
            ],
        ),
        migrations.AddField(
            model_name='meal',
            name='portions',
            field=models.ManyToManyField(to='core.Portion'),
        ),
    ]
