# Generated by Django 3.0 on 2023-08-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20230829_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='portion',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='portion',
            name='unity',
            field=models.CharField(blank=True, choices=[('g', 'g'), ('ml', 'ml')], default='g', max_length=255, null=True),
        ),
    ]
