# Generated by Django 3.0 on 2023-09-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20230829_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='food',
            name='carbs',
        ),
        migrations.RemoveField(
            model_name='food',
            name='cholestorol',
        ),
        migrations.RemoveField(
            model_name='food',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='food',
            name='kjoules',
        ),
        migrations.RemoveField(
            model_name='food',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='food',
            name='saturatedfat',
        ),
        migrations.RemoveField(
            model_name='food',
            name='sugars',
        ),
        migrations.RemoveField(
            model_name='food',
            name='totalfat',
        ),
        migrations.AddField(
            model_name='food',
            name='alcohol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Alcol (g)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='calcium',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Calcio', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Carboidrati disponibili', max_digits=8),
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('carni_fresche', 'Carni Fresche'), ('verdure_e_ortaggi', 'Verdure e Ortaggi'), ('frutta', 'Frutta'), ('legumi', 'Legumi'), ('cereali_e_derivati', 'Cereali e Derivati'), ('carni_trasformate_e_conservate', 'Carni Trasformate e Conservate'), ('fast_food_a_base_di_carne', 'Fast-Food a base di carne'), ('frattaglie', 'Frattaglie'), ('prodotti_della_pesca', 'Prodotti della Pesca'), ('latte_e_yogurt', 'Latte e Yogurt'), ('formaggi_e_latticini', 'Formaggi e Latticini'), ('olii_e_grassi', 'Olii e Grassi'), ('uova', 'Uova'), ('prodotti_vari', 'Prodotti Vari'), ('dolci', 'Dolci'), ('bevande_alcooliche', 'Bevande Alcooliche')], default='', help_text='Categoria del cibo', max_length=255),
        ),
        migrations.AddField(
            model_name='food',
            name='chemical_composition',
            field=models.TextField(blank=True, default='', help_text='Composizione chimica', null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='cholesterol',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Colesterolo', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='complex_carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Carboidrati complessi', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='copper',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Rame', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='edible_part',
            field=models.CharField(blank=True, default='', help_text='Parte edibile', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='fats',
            field=models.DecimalField(decimal_places=2, default=0, help_text='G default=0,rassi (Lipidi)', max_digits=8),
        ),
        migrations.AddField(
            model_name='food',
            name='insoluble_fiber',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Fibra insolubile', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='iron',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Ferro', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='kcal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='V default=0,alore calorico (kcal)', max_digits=8),
        ),
        migrations.AddField(
            model_name='food',
            name='kj',
            field=models.DecimalField(decimal_places=2, default=0, help_text='V default=0,alore energetico (kJ)', max_digits=8),
        ),
        migrations.AddField(
            model_name='food',
            name='magnesium',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Magnesio', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='manganese',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Manganese', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='niacin_vitamin_b3',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Niacina (Vit. B3 o PP)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='phosphorus',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Fosforo', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='potassium',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Potassio', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='proteins',
            field=models.DecimalField(decimal_places=2, default=0, help_text='P default=0,roteine', max_digits=8),
        ),
        migrations.AddField(
            model_name='food',
            name='riboflavin_vitamin_b2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Riboflavina (Vit. B2)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='selenium',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Selenio', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='soluble_fiber',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Fibra solubile', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='soluble_sugars',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Zuccheri solubili', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='thiamine_vitamin_b1',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Tiamina (Vit. B1)', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='total_fiber',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Fibra totale', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='total_monounsaturated_fats',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Monoinsaturi totali', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='total_polyunsaturated_fats',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Polinsaturi totali', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='total_saturated_fats',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Saturi totali', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_a_retinol_eq',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Vitamina A retinolo eq.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_b12',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Vitamina B12', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_b6',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Vitamina B6', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_c',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Vitamina C', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='vitamin_e',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Vitamina E', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='water',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Contenuto di acqua', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='zinc',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Zinco', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(blank=True, help_text='Nome del cibo', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Sodio', max_digits=8, null=True),
        ),
    ]
