# Generated by Django 3.0 on 2023-09-02 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20230902_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='alcohol',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Alcol (g)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='calcium',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Calcio (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='carbohydrates',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Carboidrati disponibili', max_digits=16),
        ),
        migrations.AlterField(
            model_name='food',
            name='cholesterol',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Colesterolo (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='complex_carbohydrates',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Carboidrati complessi (g)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='copper',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Rame (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='fats',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Grassi (g)', max_digits=16),
        ),
        migrations.AlterField(
            model_name='food',
            name='insoluble_fiber',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Fibra insolubile (g)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='iron',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Ferro (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='kcal',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Valore calorico (kcal)', max_digits=16),
        ),
        migrations.AlterField(
            model_name='food',
            name='kj',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Valore energetico (kJ)', max_digits=16),
        ),
        migrations.AlterField(
            model_name='food',
            name='magnesium',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Magnesio (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='manganese',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Manganese (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='niacin_vitamin_b3',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Niacina (Vit. B3 o PP) (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='phosphorus',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Fosforo (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='potassium',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Potassio (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='proteins',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Proteine (g)', max_digits=16),
        ),
        migrations.AlterField(
            model_name='food',
            name='riboflavin_vitamin_b2',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Riboflavina (Vit. B2) (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='selenium',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Selenio (µg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Sodio (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='soluble_fiber',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Fibra solubile (g)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='soluble_sugars',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Zuccheri solubili (g)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='thiamine_vitamin_b1',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Tiamina (Vit. B1) (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_fiber',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Fibra totale (g)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_monounsaturated_fats',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Monoinsaturi totali (g)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_polyunsaturated_fats',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Polinsaturi totali (g)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_saturated_fats',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Saturi totali (g)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitamin_a_retinol_eq',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Vitamina A retinolo eq. (µg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitamin_b12',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Vitamina B12 (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitamin_b6',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Vitamina B6 (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitamin_c',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Vitamina C (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='vitamin_e',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Vitamina E (mg)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='water',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Contenuto di acqua (g)', max_digits=16, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='zinc',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, help_text='Zinco (mg)', max_digits=16, null=True),
        ),
    ]
